# Site settings
title: git-issue
email: meyer.cm@gmail.com
description: >
  git-issue is an extension command to git that makes it simple to track
  issues, features, TODOs, bugs, and tasks within your repository.
baseurl: "/git-issue" # the subpath of your site, e.g. /blog/
url: "http://meyercm.github.io" # the base hostname & protocol for your site
github_username:  meyercm

# Build settings
markdown: kramdown
